backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  # This line should *not* be indented
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "EarthMCBE Docs"
    label: "Docs"
    folder: "docs/"
    fields:
      - {label: "Language", name: "language"}